use strict;
use warnings;

use Test::More tests=> 2;
use Expect;

my $e = Expect->new;
$e->raw_pty(1);
$e->log_stdout(0);
$e->spawn($^X . q{ -e 'print "iptables-save\n# Generated by\n*filter\n#";' });
$e->send("iptables-save\n");
$e->expect(1, '-re', '\n#$');
is $e->before, "iptables-save\n# Generated by\n*filter";
is $e->after, "";

done_testing;
